[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[terminal]

[colors.bright]
black = "#4d4d4d"
blue = "#caa9fa"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff92d0"
red = "#ff6e67"
white = "#e6e6e6"
yellow = "#f4f99d"

[colors.normal]
black = "#000000"
blue = "#bd93f9"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#bfbfbf"
yellow = "#f1fa8c"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[font]
size = 14.0

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[terminal.shell]
args = ["-l"]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_title = true

[window.padding]
x = 10
y = 10

[keyboard]
